### ISSUE TITLE
staticServer documentation doesn't match logic

### ISSUE THREAD

**Issue by rchl** [nuxt/tib#25]
[Document for staticServer option](https://github.com/nuxt/tib/blob/master/docs/API.md#staticserver) states this:

> - `folder` (_string_, optional)<br/>
> The path used as the webroot for the webserver. If not provided the default `folder` browser config option is used
> 

So I would assume that if `config.folder` is provided and `staticServer` is set to object like `{ port: 3333 }` then it will use `folder` from root config. But it's not the case. It seems it's only using folder from root config if `staticServer` is set to `true`:

https://github.com/nuxt/tib/blob/5f3322bd2fe77041b256cfff60ef1fa067fad06c/src/commands/static-server.js#L19-L26

**Comment by pimlie** [comment]
Seems like a bug to me indeed!

**Comment by pimlie** [comment]
Fixed in e4b5cf42f5a1a4f03840a7aab34f5629353db044

**Comment by pimlie** [comment]
Have released `0.7.2` including the above fix, thanks for the report!
