### ISSUE TITLE
Chrome detection broken in macOs Catalina

### ISSUE THREAD

**Issue by rchl** [nuxt/tib#29]
I think detection is broken again:

The original command that detects Chrome:

https://github.com/nuxt/tib/blob/28ca90b16144a6619eca5e811a3eafce60d7d29d/src/utils/detectors/chrome.js#L49

doesn't return anything anymore in Catalina.

I've removed the `end of line` match character (`$`) and then I got those results:
```
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump  | grep -E -i '(google chrome( canary)?|chromium).app'
path:               /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/77.0.3865.90/Helpers/Google Chrome Helper (GPU).app (0xa8c)
path:               /Applications/Google Chrome.app (0xc54)
path:               /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/77.0.3865.120/Helpers/Google Chrome Helper (GPU).app (0xc94)
path:               /Applications/Google Chrome Canary.app (0xce8)
path:               /Applications/Google Chrome Canary.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/79.0.3942.0/Helpers/Google Chrome Helper (GPU).app (0xd04)
```
Used this command in terminal:
`/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump  | grep -E -i '(google chrome( canary)?|chromium)\.app\b'`

So I think now the difference is the lines don't end with `*.app` but are followed by some code value (`0xd04` etc).

Here is what could be done to fix this in non-backward compatible way (obviously not acceptable, but to give an idea).

```
        ' | grep -E -i \'(google chrome( canary)?|chromium)\\.app\\b\'' +
        ' | awk \'{$1=""; $NF=""; print $0}\''
```

- replace `$` with `\b` (word boundary) maybe.
- escape dot as it wasn't before
- clear `$NF` (last component of the whole line splitted on space)

**Comment by pimlie** [comment]
Feel free to submit a pr, I am not using a mac so I cant help you with this I'm afraid.

/fyi @clarkdo As the chrome detector is copied from the Nuxt.js repo it will probably be broken there as well for Catalina?

**Comment by clarkdo** [comment]
I’ll check nuxt shortly.

**Comment by rchl** [comment]
Created PR with a fix.
I can create PR for Nuxt also once this one is approved.

**Comment by rchl** [comment]
@clarkdo friendly ping :)

**Comment by clarkdo** [comment]
Sorry, I’m in vocation recently, I’ll follow this issue ASAP.
